# Generated by Django 4.1.4 on 2023-12-10 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0002_alter_contact_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="time",
        ),
        migrations.AddField(
            model_name="contact",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 9, 19, 24, 38, 210348)
            ),
        ),
    ]
