# Generated by Django 4.1.4 on 2023-12-12 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0003_remove_contact_time_contact_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 11, 19, 40, 12, 382879)
            ),
        ),
    ]
